// This file is auto-generated by Lovable. Modified to work outside Lovable hosting.

import { supabase } from "../supabase/client";

let lovableAuth: any = null;
try {
  const { createLovableAuth } = require("@lovable.dev/cloud-auth-js");
  lovableAuth = createLovableAuth();
} catch {
  // Not running on Lovable — OAuth will use Supabase directly
}

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      // If Lovable auth is available, use it
      if (lovableAuth) {
        try {
          const result = await lovableAuth.signInWithOAuth(provider, {
            redirect_uri: opts?.redirect_uri,
            extraParams: { ...opts?.extraParams },
          });

          if (result.redirected) return result;
          if (result.error) return result;

          try {
            await supabase.auth.setSession(result.tokens);
          } catch (e) {
            return { error: e instanceof Error ? e : new Error(String(e)) };
          }
          return result;
        } catch {
          // Fall through to Supabase OAuth
        }
      }

      // Fallback: use Supabase OAuth directly
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: opts?.redirect_uri || window.location.origin,
          queryParams: opts?.extraParams,
        },
      });

      if (error) return { error };
      return { redirected: true };
    },
  },
};
